# Generated by Django 5.0.6 on 2023-09-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
